Vagrant.configure("2") do |config|

  config.vm.define "static" do | static |
    static.vm.box = "jaca1805/debian12"
    static.vm.network "private_network", ip: "192.168.33.13"

    static.vm.provider "virtualbox" do |vb|
      vb.memory = "1048"
      vb.cpus = "2"
   end

  config.vm.define "httpd" do | httpd |
    httpd.vm.box = "jaca1805/debian12"
    httpd.vm.network "private_network", ip: "192.168.33.14"

    httpd.vm.provider "virtualbox" do |vb|
      vb.memory = "1048"
      vb.cpus = "2"
   end

  config.vm.define "postgreSQL" do |postgreSQL|
    postgreSQL.vm.box = "jaca1805/debian12"
    postgreSQL.vm.network "private_network", ip: "192.168.33.15"

    postgreSQL.vm.provider "virtualbox" do |vb|
      vb.memory = "1048"
      vb.cpus = "2"
    end
end
